Spring:
  port: 3000
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/website
#    driverClassName: com.mysql.jdbc.Driver
    password: 'root'
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    database: MYSQL
    show-sql: 'true'